Allow to run tests inside docker container (#499)
There are still one error remaining with attachment file.

ERROR CatalogAdmin::ItemsTest#test_import_items_from_CSV (175.05s)
Minitest::UnexpectedError:
ArgumentError: Selenium < 3.14 with remote Chrome doesn't support
multiple file upload
test/integration/catalog_admin/csv_imports_test.rb:10:in `block in
<class:ItemsTest>'