#183568795 - Optimize choice_set edit items (#483)
* #183568795 - Optimize choice_set edit items

* Fix default values overriding custom values for new item (#485)

* Fix default values overriding custom values for new item

Note: the same problem could happens with "assign_autoincrement_values"
callback, but the case was already taken care with the same logic than
this fix.

Add two tests:
 - One for testing that default values are correctly setted.
 - One for testing that default values don't override custom value.

* Uses guards clauses for better lisibility

* Fix formating and adds comments

* Hide public list view if field is not human readable (#484)

* Disable server side field option public list view if not human readable

* Hide field option public list view if not human readable

* Disable some options for text field instead of hidding them

* Add help on formatted text field's option

* Migration for setting public list view option according to the human readable status of the field

* Fix no new line at end of file

* Reviews adaptations

 - Adapt help text for better comprehension
 - Add guard clause for better lisibility
 - Use existing bootstrap class instead of inline style

* Simplify formatted text helper

* Simplify formatted text helper (fr)

Co-authored-by: Luca Guindani <luca.guindani@gmail.com>

* Bump json5 from 1.0.1 to 1.0.2 (#487)

Bumps [json5](https://github.com/json5/json5) from 1.0.1 to 1.0.2.
- [Release notes](https://github.com/json5/json5/releases)
- [Changelog](https://github.com/json5/json5/blob/main/CHANGELOG.md)
- [Commits](https://github.com/json5/json5/compare/v1.0.1...v1.0.2)

---
updated-dependencies:
- dependency-name: json5
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Fix items custom style (#488)

* Change style description for clarification

* Fix custom style not applied correctly

* Rework headings styles

* Fix dropdown default value not working properly

* Fix and add tests

* Fix choices presenter (#489)

* Fix the character '>' to be displayed by error for hierarchical choices

* Rubocop and reformat for better lisibility

* Fix choice set presenter test

* Add test for hierarchy choice set presenter

* Rubocop and reformat for better lisibility

* Fix broken choice set test

* Add blank line after guard clause

* Remove empty line

* CR ComplexDatation (#490)

* Localize choice set import file label

* Remove between & outside search conditions for the datation field

* Add datation data to choice_set & choice api responses

* Fix special chars wrongly encoded by strip_tags method
Fix Rubocop correctable issues

* Typo

* Revert docker compose configuration

* Bump rack from 2.2.4 to 2.2.6.2 (#492)

Bumps [rack](https://github.com/rack/rack) from 2.2.4 to 2.2.6.2.
- [Release notes](https://github.com/rack/rack/releases)
- [Changelog](https://github.com/rack/rack/blob/main/CHANGELOG.md)
- [Commits](https://github.com/rack/rack/compare/2.2.4...v2.2.6.2)

---
updated-dependencies:
- dependency-name: rack
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump globalid from 1.0.0 to 1.0.1 (#493)

Bumps [globalid](https://github.com/rails/globalid) from 1.0.0 to 1.0.1.
- [Release notes](https://github.com/rails/globalid/releases)
- [Commits](https://github.com/rails/globalid/compare/v1.0.0...v1.0.1)

---
updated-dependencies:
- dependency-name: globalid
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Update rails to 6.1.7.1

* Add codeql workflow for github actions

* Fix typo in workflow

* Rename codeql workflow & remove master branch

* Fix ItemList line view error on homepage (#494)

Fix issue #486

* Bump mammoth js dependency to specific commit

* Fix export CSV for datation with choice set (#495)

* Hotfix for editor field with deleted user

* CR

* Retours Complex Datation (#496)

* CR

* pass correct allow_bc_option to AdvancedComplexDatationSearch

* CR

* Fix MultiReferenceEditor search results

* Rollback filtering in MultiReferenceEditor

* Fix pagination for MultiReferenceEditor

* Fix pictures not displayed in public list display (#497)

* Fix pictures not displayed in public list display

* Restructurates a method for better code homogeneity

* Retours complex datation search 2 (#498)

* Update rubygems to specific version in dockerfiles
Stack versions as envar in dockerfiles

* Allow to run tests inside docker container (#499)

There are still one error remaining with attachment file.

ERROR CatalogAdmin::ItemsTest#test_import_items_from_CSV (175.05s)
Minitest::UnexpectedError:
ArgumentError: Selenium < 3.14 with remote Chrome doesn't support
multiple file upload
test/integration/catalog_admin/csv_imports_test.rb:10:in `block in
<class:ItemsTest>'

* Update selenium-webdriver to avoid multiple uploads error during tests
Update readme

* Replace infinite scroll in MultiReferenceEditor by a "load more" button (avoid pagination with empty content issue)
Remove filter on fulltext searches
Update tests

* Fix filterable for summary (#500)

* Fix filterable field not displayed in public list view

* Updates tests

* Remove unused variable (#501)

* Updates locales

* Fix de, it locals

* Tests public list (#502)

* Adds tests for summary view

* Fix broken test

* Fix exclude operator for choice set fields in advanced search
Code style

* Fix user deletion (#491)

* Rubocop corrections

* Migrations for users.deleted_at

* Fix user deletion

* Unscope user for jti migration

* Use touch when destroying user

* Factorize roles usage

* Fix membership for deleted users

* Adds :inverse_of information and missings has_many relationships for User model

* Unscopes user from searches

And changes dependent params for has_many from nullify to destroy. This
is because searches are used in containers. Deleting a User must not
alter the pages containing a search container.

* CR update ChoiceSetInput

* fix - item summary (#505)

* Fix container with empty item type issue
Add tests

* Fix menu with itself as parent

* merge development

* Revert docker compose configuration

* CR

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: David Miserez <david.miserez@unil.ch>
Co-authored-by: Luca Guindani <luca.guindani@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>